[package]
name = "maze"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
codegen-units = 1
strip = true

[dependencies]
macroquad = "0.4.13"
rand = "0.8.5"
